# Generated by Django 4.2.6 on 2023-11-30 10:05

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('hours', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Discipline',
                'db_table': 'discipline',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('issue_date', models.DateField(default=datetime.datetime.now)),
                ('expiration_date', models.DateField(default=None)),
            ],
            options={
                'verbose_name': 'Document',
                'db_table': 'document',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('duties', models.CharField(max_length=200)),
                ('conditions', models.CharField(max_length=200)),
                ('requirements', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Position of employee',
                'db_table': 'position',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts_count', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=20)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mvd_app.discipline')),
            ],
            options={
                'verbose_name': 'Exam',
                'db_table': 'exam',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.BinaryField()),
                ('birth_date', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mvd_app.document')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mvd_app.position')),
            ],
            options={
                'verbose_name': 'Employee',
                'db_table': 'employee',
            },
        ),
        migrations.AddField(
            model_name='discipline',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mvd_app.employee'),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(default=datetime.datetime.now)),
                ('mark', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvd_app.employee')),
            ],
            options={
                'verbose_name': 'Certificate',
                'db_table': 'certificate',
            },
        ),
    ]
